[tool.briefcase]
project_name = "AppFuturo"
bundle = "www.olinfor.com.br"
version = "0.0.1"
url = "https://br.com.olinfor.www/appfuturo"
license = "MIT license"
author = 'Antonio Oliveira'
author_email = "antoniobatistajr@gmail.com"

[tool.briefcase.app.appfuturo]
formal_name = "AppFuturo"
description = "Testando developer mobile Python"
icon = "src/appfuturo/resources/appfuturo"
sources = ['src/appfuturo']
requires = []


[tool.briefcase.app.appfuturo.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.appfuturo.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.appfuturo.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.appfuturo.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.appfuturo.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
